# Generated by Django 4.2.7 on 2023-11-06 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, upload_to='profile_photos/')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone1', models.CharField(max_length=255, null=True)),
                ('phone2', models.CharField(max_length=255, null=True)),
                ('current_address', models.CharField(max_length=255)),
                ('permanant_address', models.CharField(max_length=255)),
                ('Education', models.CharField(max_length=255)),
                ('skills', models.CharField(max_length=255)),
                ('certifications', models.CharField(max_length=255)),
                ('resume', models.FileField(blank=True, upload_to='resume/')),
                ('profile_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
